# Generated by Django 2.2 on 2019-04-10 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_text', models.CharField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='en_ka.Category')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='en_ka.Word')),
            ],
        ),
    ]
